cookie:
  expiry_days: 30
  key: a_random_secret_key_123
  name: rag_app_cookie
credentials:
  usernames:
    jsmith:
      email: jsmith@example.com
      name: John Smith
      password: $2b$12$f0Ice0WmL8b9oEXkqyH64Oz.AMR9Z5wS207L3VpArMGPl5lMiwSdm
    mshees:
      email: shees00@gmail.com
      first_name: Muhammad
      last_name: Shees
      logged_in: false
      password: $2b$12$HwvTfu9.y9xIaNB6py9EHu8bRmuZt9UtAu0dJe7wG/WMtPr2UkmpW
      password_hint: shees-09
      roles: null
    rdoe:
      email: rdoe@example.com
      name: Rebecca Doe
      password: $2b$12$f.24yZVxac32dCtALiFb0ehIJkh8SfWcOHOOjEZXLWz28JO6cAyQe
    saqibmehdi:
      email: saqibmehdi234@gmail.com
      failed_login_attempts: 0
      first_name: Saqib
      last_name: Mehdi
      logged_in: true
      password: $2b$12$L0YRTs3pXhZB2R1lR9FWsOfa34C/AZeiUHIA.jYx2uTNmNLXTSKvO
      password_hint: Ali01
      roles: null
